services:
  server:
    build: .
    container_name: ciphermq-server
    command: srv --port 8080
    ports:
      - "8080:8080"
    networks:
      - ciphernet
    volumes:
      - mq-data:/data

  sign:
    build: .
    container_name: ciphermq-sign
    command: sign
    environment:
      - SIGN_USERNAME=${SIGN_USERNAME}  # passa o arg na hora do run. ex: SIGN_USERNAME=vini && docker compose run sign
    networks:
      - ciphernet
    volumes:
      - mq-data:/data

  client:
    build: .
    command: cli --connect server:8080
    stdin_open: true   # habilita o terminal interativo no Docker
    tty: true          # equivalente a -t
    depends_on:
      - server
    networks:
      - ciphernet
    volumes:
      - mq-data:/data

networks:
  ciphernet:
    driver: bridge

volumes:
  mq-data: 