package com.manocorbas.ciphermq.gui.components;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class MessagePanel extends javax.swing.JPanel {

    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");

    /**
     * Creates new form MessagePanel
     */
    public MessagePanel(LocalDateTime time, String ownerUsername, String content) {
        initComponents();
        buildMessage(time, ownerUsername, content);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        userLabel.setText("[time][user]:<message>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void buildMessage(LocalDateTime time, String ownerUsername, String content) {
        String formattedTime = time.format(FORMATTER);

        this.userLabel.setText("[" + formattedTime + "] [" + ownerUsername + "]: " + content);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
