package com.manocorbas.ciphermq.gui;

import com.manocorbas.ciphermq.client.Client;
import com.manocorbas.ciphermq.client.ClientCredentials;
import com.manocorbas.ciphermq.client.ClientSetup;
import com.manocorbas.ciphermq.client.ConnectRequest;
import com.manocorbas.ciphermq.common.ActionType;
import com.manocorbas.ciphermq.common.Message;
import com.manocorbas.ciphermq.gui.components.MessagePanel;
import com.manocorbas.ciphermq.util.log.Log;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;

public class Dashboard extends javax.swing.JFrame {

    private Client client;
    private boolean isLoggedIn = false;

    private String host;
    private int port;
    private String kmsHost;
    private int kmsPort;

    // Mapa: topicName → lista de mensagens acumuladas
    private final Map<String, List<Message>> topicMessages = new LinkedHashMap<>();

    // Model mutável para o JList (substitui o mock estático do initComponents)
    private final DefaultListModel<String> topicsListModel = new DefaultListModel<>();

    /**
     * Creates new form Dashboard
     */
    public Dashboard(String host, int port, String kmsHost, int kmsPort) {
        this.port = port;
        this.host = host;
        this.kmsHost = kmsHost;
        this.kmsPort = kmsPort;

        initComponents();

        topicsList.setModel(topicsListModel);

        this.pack();

        Log.info("GUI", "GUI started");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        appNameLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        usernameTextField = new javax.swing.JTextField();
        navbarPanel = new javax.swing.JPanel();
        topicsLabel = new javax.swing.JLabel();
        topicsScrollPane = new javax.swing.JScrollPane();
        topicsList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        topicInteractionTextArea = new javax.swing.JTextArea();
        createButton = new javax.swing.JButton();
        subButton = new javax.swing.JButton();
        topicPanel = new javax.swing.JPanel();
        topicLabel = new javax.swing.JLabel();
        topicInfoLabel = new javax.swing.JLabel();
        messagesScrollPane = new javax.swing.JScrollPane();
        messagesPanel = new javax.swing.JPanel();
        bottomBarPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        unsubButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        appNameLabel.setText("CipherMQ!");

        loginButton.setText("login");
        loginButton.addActionListener(this::loginButtonActionPerformed);

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(appNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        headerPanelLayout.setVerticalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(headerPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(headerPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 45,
                                                        Short.MAX_VALUE)
                                                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(appNameLabel, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));

        topicsLabel.setText("Topics");

        topicsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        topicsScrollPane.setViewportView(topicsList);

        topicInteractionTextArea.setColumns(20);
        topicInteractionTextArea.setRows(5);
        jScrollPane2.setViewportView(topicInteractionTextArea);

        createButton.setText("create");
        createButton.setEnabled(false);
        createButton.addActionListener(this::createButtonActionPerformed);

        subButton.setText("sub");
        subButton.setEnabled(false);
        subButton.addActionListener(this::subButtonActionPerformed);

        javax.swing.GroupLayout navbarPanelLayout = new javax.swing.GroupLayout(navbarPanel);
        navbarPanel.setLayout(navbarPanelLayout);
        navbarPanelLayout.setHorizontalGroup(
                navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(navbarPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(navbarPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(topicsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                        .addComponent(topicsLabel, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(navbarPanelLayout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(navbarPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(createButton,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(subButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE))))
                                .addContainerGap()));
        navbarPanelLayout.setVerticalGroup(
                navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(navbarPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(topicsLabel)
                                .addGap(18, 18, 18)
                                .addComponent(topicsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 317,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(navbarPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(navbarPanelLayout.createSequentialGroup()
                                                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(subButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        topicLabel.setText("Topic");

        topicInfoLabel.setText("Topic-Info");

        javax.swing.GroupLayout messagesPanelLayout = new javax.swing.GroupLayout(messagesPanel);
        messagesPanel.setLayout(messagesPanelLayout);
        messagesPanelLayout.setHorizontalGroup(
                messagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 424, Short.MAX_VALUE));
        messagesPanelLayout.setVerticalGroup(
                messagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 326, Short.MAX_VALUE));

        messagesScrollPane.setViewportView(messagesPanel);

        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        jScrollPane1.setViewportView(messageTextArea);

        sendButton.setText("Send");
        sendButton.setEnabled(false);
        sendButton.addActionListener(this::sendButtonActionPerformed);

        javax.swing.GroupLayout bottomBarPanelLayout = new javax.swing.GroupLayout(bottomBarPanel);
        bottomBarPanel.setLayout(bottomBarPanelLayout);
        bottomBarPanelLayout.setHorizontalGroup(
                bottomBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bottomBarPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)));
        bottomBarPanelLayout.setVerticalGroup(
                bottomBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bottomBarPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(bottomBarPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        unsubButton.setText("unsub");
        unsubButton.setEnabled(false);
        unsubButton.addActionListener(this::unsubButtonActionPerformed);

        javax.swing.GroupLayout topicPanelLayout = new javax.swing.GroupLayout(topicPanel);
        topicPanel.setLayout(topicPanelLayout);
        topicPanelLayout.setHorizontalGroup(
                topicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(topicPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(topicPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(messagesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                Short.MAX_VALUE)
                                        .addGroup(topicPanelLayout.createSequentialGroup()
                                                .addComponent(topicLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(topicInfoLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(unsubButton))
                                        .addComponent(bottomBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        topicPanelLayout.setVerticalGroup(
                topicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(topicPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        topicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(topicLabel)
                                                .addComponent(topicInfoLabel)
                                                .addComponent(unsubButton))
                                .addGap(18, 18, 18)
                                .addComponent(messagesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 311,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bottomBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(navbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(topicPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(navbarPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(topicPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginButtonActionPerformed
        Log.debug("GUI", "Initializing client");

        String username = getStringAndValidateFrom(usernameTextField);

        if (username == null) {
            return;
        }

        ClientCredentials creds = null;
        try {
            creds = ClientSetup.load(username);
        }

        // If the credentials were not found, we'll request a new one
        catch (IllegalStateException ignored) {}

        catch (Exception e) {
            Log.error("GUI", "Error while loading credential", e);
            return;
        }

        Client client = new Client();

        ConnectRequest request = new ConnectRequest(this.host, this.port, this.kmsHost, this.kmsPort, creds);

        try {
            client.connect(request);
        } catch (Exception e) {
            Log.error("GUI", "Error while connecting to broker", e);
            return;
        }

        this.client = client;
        this.isLoggedIn = true;

        this.loginButton.setEnabled(!isLoggedIn);
        this.createButton.setEnabled(isLoggedIn);
        this.subButton.setEnabled(isLoggedIn);
        this.sendButton.setEnabled(isLoggedIn);
        this.unsubButton.setEnabled(isLoggedIn);
        this.usernameTextField.setEditable(!isLoggedIn);
        this.usernameTextField.setText(username);

        // popula os tópicos que já existem antes de abrir
        for (String topic : client.getSubscribedIn()) {
            topicMessages.put(topic, new java.util.ArrayList<>());
            topicsListModel.addElement(topic);
        }

        topicsList.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                renderSelectedTopic();
            }
        });

        startMessageDispatcher();
    }// GEN-LAST:event_loginButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createButtonActionPerformed
        String topic = getStringAndValidateFrom(topicInteractionTextArea);

        if (topic == null) {
            return;
        }

        client.createTopic(topic);

        try {
            client.fetchTopics();
        } catch (Exception e) {
            Log.warn("GUI", "Failed to refresh topics: " + e.getMessage());
        }

        populateAndRender(topic);
    }// GEN-LAST:event_createButtonActionPerformed

    private void subButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_subButtonActionPerformed
        String topic = getStringAndValidateFrom(topicInteractionTextArea);

        if (topic == null) {
            return;
        }

        client.subscribe(topic);

        try {
            client.fetchTopics();
        } catch (Exception e) {
            Log.warn("GUI", "Failed to refresh topics: " + e.getMessage());
        }

        populateAndRender(topic);
    }// GEN-LAST:event_subButtonActionPerformed

    private void unsubButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_unsubButtonActionPerformed
        String selected = topicsList.getSelectedValue();

        if (selected == null)
            return;

        client.unsubscribe(selected);

        try {
            client.fetchTopics();
        } catch (Exception e) {
            Log.warn("GUI", "Failed to refresh topics: " + e.getMessage());
        }

        populateAndRender(null);
    }// GEN-LAST:event_unsubButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sendButtonActionPerformed
        String messageContent = getStringAndValidateFrom(messageTextArea);
        String topic = topicsList.getSelectedValue();

        if (messageContent == null || topic == null) {
            return;
        }

        try {
            client.publish(topic, messageContent);
        } catch (Exception e) {
            Log.error("GUI", e.getMessage(), e);
        }
    }// GEN-LAST:event_sendButtonActionPerformed

    private String getStringAndValidateFrom(javax.swing.text.JTextComponent textComponent) {
        String text = textComponent.getText();

        text = text.strip();

        textComponent.setText("");
        return text.isBlank() ? null : text;
    }

    // This will ensure that the topics list will be updated after
    // working like a "refresh" button
    private void populateAndRender(String topicToSelect) {

        // Cleans for rebuild
        topicsListModel.clear();

        // rebuilds based on SubscribedIn()
        for (String t : client.getSubscribedIn()) {
            // mantém mensagens já acumuladas, só adiciona ao model visual
            topicMessages.putIfAbsent(t, new ArrayList<>());
            topicsListModel.addElement(t);
        }

        // on unsub, removes the message map
        topicMessages.keySet().retainAll(client.getSubscribedIn());

        // selects the topic
        if (topicToSelect != null) {
            topicsList.setSelectedValue(topicToSelect, true);
        } else {
            topicsList.clearSelection();
            renderSelectedTopic();
        }
    }

    private void startMessageDispatcher() {
        Thread dispatcher = new Thread(() -> {
            while (true) {
                try {
                    Message msg = client.getMessageQueue().poll();

                    if (msg == null) {
                        Thread.sleep(100);
                        continue;
                    }

                    if (msg.action() != ActionType.PUBLISH) {
                        client.getMessageQueue().add(msg);
                        Thread.sleep(50);
                        continue;
                    }

                    // SwingUtilities garante que a atualização de UI
                    // acontece na EDT (Event Dispatch Thread) do Swing
                    SwingUtilities.invokeLater(() -> appendToTopic(msg));

                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    break;
                }
            }
        });
        dispatcher.setDaemon(true); // morre junto com a app
        dispatcher.start();
    }

    /**
     * Recebe uma mensagem e a armazena no tópico correto. Se o tópico ainda não
     * existe na lista, adiciona. Se o tópico estiver selecionado no momento,
     * re-renderiza.
     */
    private void appendToTopic(Message msg) {
        String topic = msg.topic();

        if (topic == null) {
            return;
        }

        // garante que o tópico existe no mapa e na JList
        if (!topicMessages.containsKey(topic)) {
            topicMessages.put(topic, new ArrayList<>());
            topicsListModel.addElement(topic);
        }

        // formata e acumula a mensagem
        topicMessages.get(topic).add(msg);

        // atualiza o painel só se esse tópico estiver visível agora
        String selected = topicsList.getSelectedValue();
        if (topic.equals(selected)) {
            renderSelectedTopic();
        }
    }

    /**
     * Renderiza no messagesPanel as mensagens do tópico selecionado. Limpa o
     * painel e reconstrói os painéis de mensagem.
     */
    private void renderSelectedTopic() {
        String selected = topicsList.getSelectedValue();

        // atualiza o label do header do topicPanel
        topicLabel.setText(selected != null ? selected : "Topic");

        messagesPanel.removeAll();
        messagesPanel.setLayout(new BoxLayout(messagesPanel, BoxLayout.Y_AXIS));

        if (selected != null && topicMessages.containsKey(selected)) {
            for (Message msg : topicMessages.get(selected)) {
                String sender = msg.sender() != null ? msg.sender() : "unknown";

                MessagePanel card = new MessagePanel(msg.time(), sender, msg.content());
                messagesPanel.add(card);
            }
        }

        messagesPanel.revalidate();
        messagesPanel.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JPanel bottomBarPanel;
    private javax.swing.JButton createButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JPanel messagesPanel;
    private javax.swing.JScrollPane messagesScrollPane;
    private javax.swing.JPanel navbarPanel;
    private javax.swing.JButton sendButton;
    private javax.swing.JButton subButton;
    private javax.swing.JLabel topicInfoLabel;
    private javax.swing.JTextArea topicInteractionTextArea;
    private javax.swing.JLabel topicLabel;
    private javax.swing.JPanel topicPanel;
    private javax.swing.JLabel topicsLabel;
    private javax.swing.JList<String> topicsList;
    private javax.swing.JScrollPane topicsScrollPane;
    private javax.swing.JButton unsubButton;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
