package com.manocorbas.ciphermq.gui;

import com.manocorbas.ciphermq.client.Client;
import com.manocorbas.ciphermq.common.Message;
import com.manocorbas.ciphermq.util.log.Log;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public class Dashboard extends javax.swing.JFrame {

    private Client client;

    // Mapa: topicName → lista de mensagens acumuladas
    private final Map<String, List<String>> topicMessages = new LinkedHashMap<>();

    // Model mutável para o JList (substitui o mock estático do initComponents)
    private final DefaultListModel<String> topicsListModel = new DefaultListModel<>();

    /**
     * Creates new form Dashboard
     */
    public Dashboard(Client client) {
        initComponents();
        this.client = client;

        topicsList.setModel(topicsListModel);

        // popula os tópicos que já existem antes de abrir
        for (String topic : client.getSubscribedIn()) {
            topicMessages.put(topic, new java.util.ArrayList<>());
            topicsListModel.addElement(topic);
        }

        topicsList.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                renderSelectedTopic();
            }
        });

        startMessageDispatcher();
        this.pack();

        Log.info("GUI", "GUI started");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        appNameLabel = new javax.swing.JLabel();
        navbarPanel = new javax.swing.JPanel();
        topicsLabel = new javax.swing.JLabel();
        topicsScrollPane = new javax.swing.JScrollPane();
        topicsList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        topicInteractionTextArea = new javax.swing.JTextArea();
        createButton = new javax.swing.JButton();
        subButton = new javax.swing.JButton();
        topicPanel = new javax.swing.JPanel();
        topicLabel = new javax.swing.JLabel();
        topicInfoLabel = new javax.swing.JLabel();
        messagesScrollPane = new javax.swing.JScrollPane();
        messagesPanel = new javax.swing.JPanel();
        messagePanelmock = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        bottomBarPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        unsubButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        appNameLabel.setText("CipherMQ!");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(appNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        headerPanelLayout.setVerticalGroup(
                headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(appNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                .addContainerGap()));

        topicsLabel.setText("Topics");

        topicsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        topicsScrollPane.setViewportView(topicsList);

        topicInteractionTextArea.setColumns(20);
        topicInteractionTextArea.setRows(5);
        jScrollPane2.setViewportView(topicInteractionTextArea);

        createButton.setText("create");

        subButton.setText("sub");

        javax.swing.GroupLayout navbarPanelLayout = new javax.swing.GroupLayout(navbarPanel);
        navbarPanel.setLayout(navbarPanelLayout);
        navbarPanelLayout.setHorizontalGroup(
                navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(navbarPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(navbarPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(topicsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                        .addComponent(topicsLabel, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(navbarPanelLayout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(navbarPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(createButton,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(subButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE))))
                                .addContainerGap()));
        navbarPanelLayout.setVerticalGroup(
                navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(navbarPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(topicsLabel)
                                .addGap(18, 18, 18)
                                .addComponent(topicsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 317,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(navbarPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(navbarPanelLayout.createSequentialGroup()
                                                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(subButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        topicLabel.setText("Topic");

        topicInfoLabel.setText("Topic-Info");

        userLabel.setText("[ User ] :");

        messageLabel.setText("[ Message ]");

        javax.swing.GroupLayout messagePanelmockLayout = new javax.swing.GroupLayout(messagePanelmock);
        messagePanelmock.setLayout(messagePanelmockLayout);
        messagePanelmockLayout.setHorizontalGroup(
                messagePanelmockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(messagePanelmockLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(messagePanelmockLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 311,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(userLabel))
                                .addContainerGap(95, Short.MAX_VALUE)));
        messagePanelmockLayout.setVerticalGroup(
                messagePanelmockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(messagePanelmockLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(userLabel)
                                .addGap(18, 18, 18)
                                .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                .addContainerGap()));

        javax.swing.GroupLayout messagesPanelLayout = new javax.swing.GroupLayout(messagesPanel);
        messagesPanel.setLayout(messagesPanelLayout);
        messagesPanelLayout.setHorizontalGroup(
                messagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(messagesPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(messagePanelmock, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        messagesPanelLayout.setVerticalGroup(
                messagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(messagesPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(messagePanelmock, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(220, Short.MAX_VALUE)));

        messagesScrollPane.setViewportView(messagesPanel);

        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        jScrollPane1.setViewportView(messageTextArea);

        sendButton.setText("Send");

        javax.swing.GroupLayout bottomBarPanelLayout = new javax.swing.GroupLayout(bottomBarPanel);
        bottomBarPanel.setLayout(bottomBarPanelLayout);
        bottomBarPanelLayout.setHorizontalGroup(
                bottomBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bottomBarPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)));
        bottomBarPanelLayout.setVerticalGroup(
                bottomBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bottomBarPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(bottomBarPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        unsubButton.setText("unsub");

        javax.swing.GroupLayout topicPanelLayout = new javax.swing.GroupLayout(topicPanel);
        topicPanel.setLayout(topicPanelLayout);
        topicPanelLayout.setHorizontalGroup(
                topicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(topicPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(topicPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(messagesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                Short.MAX_VALUE)
                                        .addGroup(topicPanelLayout.createSequentialGroup()
                                                .addComponent(topicLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(topicInfoLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(unsubButton))
                                        .addComponent(bottomBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        topicPanelLayout.setVerticalGroup(
                topicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(topicPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        topicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(topicLabel)
                                                .addComponent(topicInfoLabel)
                                                .addComponent(unsubButton))
                                .addGap(18, 18, 18)
                                .addComponent(messagesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 311,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bottomBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(navbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(topicPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(navbarPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(topicPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startMessageDispatcher() {
        Thread dispatcher = new Thread(() -> {
            while (true) {
                try {
                    Message msg = client.getMessageQueue().poll();
                    if (msg != null) {
                        // SwingUtilities garante que a atualização de UI
                        // acontece na EDT (Event Dispatch Thread) do Swing
                        SwingUtilities.invokeLater(() -> appendToTopic(msg));
                    } else {
                        Thread.sleep(100);
                    }
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    break;
                }
            }
        });
        dispatcher.setDaemon(true); // morre junto com a app
        dispatcher.start();
    }

    /**
     * Recebe uma mensagem e a armazena no tópico correto. Se o tópico ainda não
     * existe na lista, adiciona. Se o tópico estiver selecionado no momento,
     * re-renderiza.
     */
    private void appendToTopic(Message msg) {
        String topic = msg.topic();

        // garante que o tópico existe no mapa e na JList
        if (!topicMessages.containsKey(topic)) {
            topicMessages.put(topic, new ArrayList<>());
            topicsListModel.addElement(topic);
        }

        // formata e acumula a mensagem
        String formatted = "[" + msg.action() + "] " + msg.content();
        topicMessages.get(topic).add(formatted);

        // atualiza o painel só se esse tópico estiver visível agora
        String selected = topicsList.getSelectedValue();
        if (topic.equals(selected)) {
            renderSelectedTopic();
        }
    }

    /**
     * Renderiza no messagesPanel as mensagens do tópico selecionado. Limpa o
     * painel e reconstrói os painéis de mensagem.
     */
    private void renderSelectedTopic() {
        String selected = topicsList.getSelectedValue();

        // atualiza o label do header do topicPanel
        topicLabel.setText(selected != null ? selected : "Topic");

        messagesPanel.removeAll();
        messagesPanel.setLayout(new BoxLayout(messagesPanel, BoxLayout.Y_AXIS));

        if (selected != null && topicMessages.containsKey(selected)) {
            for (String msg : topicMessages.get(selected)) {
                // reutiliza o estilo do messagePanelmock: userLabel + messageLabel
                JPanel card = new JPanel();
                card.setLayout(new BoxLayout(card, javax.swing.BoxLayout.Y_AXIS));
                card.setBorder(BorderFactory.createEmptyBorder(4, 8, 4, 8));

                JLabel user = new JLabel("[ " + selected + " ]:");
                JLabel content = new JLabel(msg);

                card.add(user);
                card.add(content);
                messagesPanel.add(card);
            }
        }

        messagesPanel.revalidate();
        messagesPanel.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JPanel bottomBarPanel;
    private javax.swing.JButton createButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPanel messagePanelmock;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JPanel messagesPanel;
    private javax.swing.JScrollPane messagesScrollPane;
    private javax.swing.JPanel navbarPanel;
    private javax.swing.JButton sendButton;
    private javax.swing.JButton subButton;
    private javax.swing.JLabel topicInfoLabel;
    private javax.swing.JTextArea topicInteractionTextArea;
    private javax.swing.JLabel topicLabel;
    private javax.swing.JPanel topicPanel;
    private javax.swing.JLabel topicsLabel;
    private javax.swing.JList<String> topicsList;
    private javax.swing.JScrollPane topicsScrollPane;
    private javax.swing.JButton unsubButton;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
